### ISSUE TITLE
能否补充下真机不插线远程调试的原理文档？

### ISSUE THREAD

**Issue by gemmi** [songyaru/doc-backup#1]
真机插线远程调试的原理讲的很好，但是不插线远程调试更方便， 希望能分享下原理， 谢谢。

**Comment by songyaru** [comment]
> 真机插线远程调试的原理讲的很好，但是不插线远程调试更方便， 希望能分享下原理， 谢谢。

不好意思，人太懒了，一直没回复。
由于去年已从百度离职了，所以真机调试这块内容已经不再搞了，大致说一下原理：
主要是通过 ngrok 做内网穿透，将 adb 传输的那层数据放到网络上。
另外还有一种方案是基于 nodejs 的调试方案做的，因为小游戏、小程序的框架已经去掉了webview，直接在 app 中嵌入了  V8 ，通过实现 V8 inspector 的接口就可以用标准的远程调试协议来调试。可以参考https://v8.dev/docs/inspector 和 https://medium.com/@hyperandroid/v8-inspector-from-an-embedder-standpoint-7f9c0472e2b7
